# Generated by Django 6.0 on 2025-12-17 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_App_1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo_app_1',
            old_name='complted',
            new_name='completed',
        ),
    ]
